coverage:
    status:
        project:
            default:
                target: 75
                # range: 75...100
                round: down
                if_ci_failed: error
                flags:
                    - Apex
        patch: off
